services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        image: php:7.3-fpm
        volumes:
            - .:/var/www/html
        environment:
            - GEOFS_BASE_PAGE=https://giv-geofs.uni-muenster.de
